// 스스로학습 > 색깔에 맞는 학생 그룹 목록 > 드릴학습 참여건수
// API 작업 실제 종료일 2024-04-15
// 테이블 정의가 필요하여 테이블 생성 대기중

const data = {
    success: true,
    dataSize: 1,
    timestamp: '2024-03-29 01:33:02',
    data: [
        {
            dt: null,
            semId: null,
            clssUuid: null,
            tchrUuid: null,
            studUuid: null,
            hstTyp: null,
            colorLstnnCnt: 32,
            colorSpkngCnt: 30,
            colorRedngCnt: 28,
            colorWritngCnt: 26,
            colorViewCnt: 24,
            colorPrsntCnt: 22,
            dsgnId: null,
            dsgnPrgrsRt: null,
            dsgnUseInfo: null,
            dsgnUseColorCnt: null,
            etlDttm: '2024-03-20T16:27:03',
            stampId: 1,
            fileName: '파일명1',
            imgSrc: '/images/temp/img_bk_thumb.png'
        },
        {
            dt: null,
            semId: null,
            clssUuid: null,
            tchrUuid: null,
            studUuid: null,
            hstTyp: null,
            colorLstnnCnt: 19,
            colorSpkngCnt: 19,
            colorRedngCnt: 19,
            colorWritngCnt: 19,
            colorViewCnt: 19,
            colorPrsntCnt: 19,
            dsgnId: null,
            dsgnPrgrsRt: null,
            dsgnUseInfo: null,
            dsgnUseColorCnt: null,
            etlDttm: '2024-03-21T17:40:08',
            stampId: 2,
            fileName: '파일명2',
            imgSrc: '/images/temp/img_bk_thumb.png'
        },
        {
            dt: null,
            semId: null,
            clssUuid: null,
            tchrUuid: null,
            studUuid: null,
            hstTyp: null,
            colorLstnnCnt: 22,
            colorSpkngCnt: 20,
            colorRedngCnt: 18,
            colorWritngCnt: 16,
            colorViewCnt: 14,
            colorPrsntCnt: 12,
            dsgnId: null,
            dsgnPrgrsRt: null,
            dsgnUseInfo: null,
            dsgnUseColorCnt: null,
            etlDttm: '2024-03-21T17:07:35',
            stampId: 3,
            fileName: '파일명3',
            imgSrc: '/images/temp/img_bk_thumb.png'
        },
        {
            dt: null,
            semId: null,
            clssUuid: null,
            tchrUuid: null,
            studUuid: null,
            hstTyp: null,
            colorLstnnCnt: 22,
            colorSpkngCnt: 20,
            colorRedngCnt: 18,
            colorWritngCnt: 16,
            colorViewCnt: 14,
            colorPrsntCnt: 12,
            dsgnId: null,
            dsgnPrgrsRt: null,
            dsgnUseInfo: null,
            dsgnUseColorCnt: null,
            etlDttm: '2024-03-21T17:07:35',
            stampId: 3,
            fileName: '파일명3',
            imgSrc: '/images/temp/img_bk_thumb.png'
        },
        {
            dt: null,
            semId: null,
            clssUuid: null,
            tchrUuid: null,
            studUuid: null,
            hstTyp: null,
            colorLstnnCnt: 22,
            colorSpkngCnt: 20,
            colorRedngCnt: 18,
            colorWritngCnt: 16,
            colorViewCnt: 14,
            colorPrsntCnt: 12,
            dsgnId: null,
            dsgnPrgrsRt: null,
            dsgnUseInfo: null,
            dsgnUseColorCnt: null,
            etlDttm: '2024-03-21T17:07:35',
            stampId: 2,
            fileName: '파일명3',
            imgSrc: '/images/temp/img_bk_thumb.png'
        },
        {
            dt: null,
            semId: null,
            clssUuid: null,
            tchrUuid: null,
            studUuid: null,
            hstTyp: null,
            colorLstnnCnt: 22,
            colorSpkngCnt: 20,
            colorRedngCnt: 18,
            colorWritngCnt: 16,
            colorViewCnt: 14,
            colorPrsntCnt: 12,
            dsgnId: null,
            dsgnPrgrsRt: null,
            dsgnUseInfo: null,
            dsgnUseColorCnt: null,
            etlDttm: '2024-03-21T17:07:35',
            stampId: 2,
            fileName: '파일명3',
            imgSrc: '/images/temp/img_bk_thumb.png'
        },
        {
            dt: null,
            semId: null,
            clssUuid: null,
            tchrUuid: null,
            studUuid: null,
            hstTyp: null,
            colorLstnnCnt: 22,
            colorSpkngCnt: 20,
            colorRedngCnt: 18,
            colorWritngCnt: 16,
            colorViewCnt: 14,
            colorPrsntCnt: 12,
            dsgnId: null,
            dsgnPrgrsRt: null,
            dsgnUseInfo: null,
            dsgnUseColorCnt: null,
            etlDttm: '2024-03-21T17:07:35',
            stampId: 1,
            fileName: '파일명3',
            imgSrc: '/images/temp/img_bk_thumb.png'
        }
    ]
};

export default defineEventHandler(() => {
    return data;
});
