// Touch VOCA 학습 팝업
// 400 에러 발생
// API 개발완료
// API 작업 실제 종료일 2024-03-25

const data = {
    dataSize: 0,
    timestamp: '2024-04-03T09:12:48.571Z',
    httpCode: 0,
    message: 'string',
    data: [
        {
            etlDttm: '2024-05-02T00:36:27.250Z',
            dt: '2024-05-02',
            semId: 0,
            clssUuid: 'string',
            tchrUuid: 'string',
            studUuid: 'string',
            lmTypAkey: 'string',
            chId: 0,
            sessId: 0,
            wrdKnowCnt: 33,
            wrdLittleknowCnt: 22,
            wrdUnknownCnt: 33,
            wrdTot: 88,
            avgAnswrRt: 77,
            startDt: '2024-05-02',
            endDt: '2024-05-02',
            eduOfficeCode: 'string'
        },
        {
            etlDttm: '2024-05-02T00:36:27.250Z',
            dt: '2024-05-02',
            semId: 0,
            clssUuid: 'string',
            tchrUuid: 'string',
            studUuid: 'string',
            lmTypAkey: 'string',
            chId: 0,
            sessId: 0,
            wrdKnowCnt: 28,
            wrdLittleknowCnt: 20,
            wrdUnknownCnt: 30,
            wrdTot: 78,
            avgAnswrRt: 87,
            startDt: '2024-05-02',
            endDt: '2024-05-02',
            eduOfficeCode: 'string'
        },
        {
            etlDttm: '2024-05-02T00:36:27.250Z',
            dt: '2024-05-02',
            semId: 0,
            clssUuid: 'string',
            tchrUuid: 'string',
            studUuid: 'string',
            lmTypAkey: 'string',
            chId: 0,
            sessId: 0,
            wrdKnowCnt: 33,
            wrdLittleknowCnt: 22,
            wrdUnknownCnt: 33,
            wrdTot: 88,
            avgAnswrRt: 77,
            startDt: '2024-05-02',
            endDt: '2024-05-02',
            eduOfficeCode: 'string'
        },
        {
            etlDttm: '2024-05-02T00:36:27.250Z',
            dt: '2024-05-02',
            semId: 0,
            clssUuid: 'string',
            tchrUuid: 'string',
            studUuid: 'string',
            lmTypAkey: 'string',
            chId: 0,
            sessId: 0,
            wrdKnowCnt: 29,
            wrdLittleknowCnt: 18,
            wrdUnknownCnt: 23,
            wrdTot: 70,
            avgAnswrRt: 92,
            startDt: '2024-05-02',
            endDt: '2024-05-02',
            eduOfficeCode: 'string'
        },
        {
            etlDttm: '2024-05-02T00:36:27.250Z',
            dt: '2024-05-02',
            semId: 0,
            clssUuid: 'string',
            tchrUuid: 'string',
            studUuid: 'string',
            lmTypAkey: 'string',
            chId: 0,
            sessId: 0,
            wrdKnowCnt: 33,
            wrdLittleknowCnt: 22,
            wrdUnknownCnt: 33,
            wrdTot: 88,
            avgAnswrRt: 77,
            startDt: '2024-05-02',
            endDt: '2024-05-02',
            eduOfficeCode: 'string'
        },
        {
            etlDttm: '2024-05-02T00:36:27.250Z',
            dt: '2024-05-02',
            semId: 0,
            clssUuid: 'string',
            tchrUuid: 'string',
            studUuid: 'string',
            lmTypAkey: 'string',
            chId: 0,
            sessId: 0,
            wrdKnowCnt: 30,
            wrdLittleknowCnt: 20,
            wrdUnknownCnt: 30,
            wrdTot: 80,
            avgAnswrRt: 92,
            startDt: '2024-05-02',
            endDt: '2024-05-02',
            eduOfficeCode: 'string'
        },
        {
            etlDttm: '2024-05-02T00:36:27.250Z',
            dt: '2024-05-02',
            semId: 0,
            clssUuid: 'string',
            tchrUuid: 'string',
            studUuid: 'string',
            lmTypAkey: 'string',
            chId: 0,
            sessId: 0,
            wrdKnowCnt: 13,
            wrdLittleknowCnt: 12,
            wrdUnknownCnt: 23,
            wrdTot: 48,
            avgAnswrRt: 87,
            startDt: '2024-05-02',
            endDt: '2024-05-02',
            eduOfficeCode: 'string'
        }
    ]
};

export default defineEventHandler(() => {
    return data;
});
